### PR TITLE
Resolve interpolateColor return type

### PR DESCRIPTION
**Pull request by hosseinmd**

### CODE REVIEW

**Comment by wcandillon** [comment]
I don't have ColorValue in my type definition, what is it defined as?

**Comment by hosseinmd** [comment]
This is a type which react-native sets it to color properties. And reanimated wrapped that with Animated.Node.

This is React-native type definition
```js
declare const OpaqueColorValue: unique symbol;
type OpaqueColorValue = typeof OpaqueColorValue;

export type ColorValue = string | OpaqueColorValue;

export interface ViewStyle extends FlexStyle, ShadowStyleIOS, TransformsStyle {
   // Other types
    backgroundColor?: ColorValue;
    borderBottomColor?: ColorValue;
    borderColor?: ColorValue;
    borderEndColor?: ColorValue;
}

**Comment by hosseinmd** [comment]
You define the return type of interpolateColor `Animated.Node<number>` but the color is not a number node.

**Comment by ukasyahrz** [comment]
It's Animated.Node<string>

**Comment by hosseinmd** [comment]
Right, that is about reanimated AnimateStyle.

**Comment by hosseinmd** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/1224

**Comment by wcandillon** [comment]
Thks for looking into it, I'm running into this issue too ;-)

**Pull request closed without merging**
