### PR TITLE
🛠 Reanimated 2 Support

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Might be worthwhile to mention that this, by itself, drops support for version < 2.

**Comment by hosseinmd** [comment]
V2 is not supported web yet, for this reason migrating to v2 is hard.

**Comment by likern** [comment]
> V2 is not supported web yet, for this reason migrating to v2 is hard.

It might be major version change. Previous users continue to use previous version until react-native-web will get support (if any).
New users will be able to utilize reanimated V2.

**Comment by terrysahaidak** [comment]
I'm currently working on web support https://github.com/software-mansion/react-native-reanimated/pull/985

**Comment by wcandillon** [comment]
The v2 version will still export the v1 functions: https://github.com/wcandillon/react-native-redash/pull/330

**Pull request closed without merging**
