### PR TITLE
feat(📤): export interface `InteractableProps`

### PR DESCRIPTION
**Pull request by ken0x0a**
I wanted to extend `InteractableProps`.

### CODE REVIEW

**Comment by wcandillon** [comment]
done (I love the emoji btw) but please beware that we don't support this component at the moment ;-)

**Comment by ken0x0a** [comment]
@wcandillon Thank you for quick ⏳response!
I love your many ideas (including emoji & github repos & Youtube) & activities :D
I learned from you a lot 🙏

**Comment by wcandillon** [comment]
You've made my day: Thank you :)

**Pull request merged**
