### PR TITLE
Allow passing arbitrary props to ReText component

### LINKED ISSUE #500: Allow passing arbitrary props like testID to the ReText TextInput component
Currently `ReText` drops additional props. Would like them to be passed on to the underlying text input instead.

### PR DESCRIPTION
**Pull request by Jyrno42**
fix #500

### CODE REVIEW

**Comment by wcandillon** [comment]
Looks great, could the same be achieve with `TextProps extends TextInputProps`?

**Comment by Jyrno42** [comment]
I used a separate prop since I wanted to avoid people setting "value" prop via this. But now that I read it it's still possible to do that. I guess changing it to be `TextProps extends Omit<TextInputProps, 'value'>` would be the best solution.

**Comment by Jyrno42** [comment]
It's updated now and worked in my app too.

**Comment by wcandillon** [comment]
so good thks!

**Pull request merged**
