### PR TITLE
v8: New animation runners and gesture decorators

### PR DESCRIPTION
**Pull request by wcandillon**
* Remove limit()
* New animation runners
* New gesture decorators

TODOs:
* Unify animation runners:
  * autoStart option

### CODE REVIEW

**Comment by wcandillon** [comment]
Agreed, let do a bigger release that we will push when necessary

**Comment by wcandillon** [comment]
I'm excited, this is converging in the right direction :))

**Comment by dsznajder** [comment]
Me too! Especially that we can prom it as something really cool and even document Reanimated package here to be clear and useful :) I will DM you with ideas :)

**Pull request merged**
