### PR TITLE
Reset frame time when toValue changes

### PR DESCRIPTION
**Pull request by marcusstenbeck**
After much trial and error (and learning) I finally figured out how to reset the animation timer when a value changes. This looks and feels much nicer than having the frame timer keep running when the `toValue` changes.

I'm sure it can be improved on, but I thought I'd shine a flashlight on this, and let you decide if it's worth making an actual change. If so, it probably has equivalent solutions in the other animation functions.

Kapture 2019-05-24 at 15 59 22
Kapture 2019-05-24 at 16 01 39

I've attached my messy scratch-pad code if you would like to try it out (add imports etc before running the code).

```
function runTiming2(clock, value, config) {
  const state = {
    finished: new Value(0),
    position: new Value(0),
    time: new Value(0),
    frameTime: new Value(0)
  };

  return block([
    onChange(config.toValue, set(state.frameTime, 0)),
    cond(clockRunning(clock), 0, [
      set(state.finished, 0),
      set(state.time, 0),
      set(state.position, value),
      set(state.frameTime, 0),
      startClock(clock)
    ]),
    timing(clock, state, config),
    cond(state.finished, stopClock(clock)),
    state.position
  ]);
}

class TogglingThing extends React.Component {
  constructor(props) {
    super(props);
    const { on } = props;

    const initialValue = on ? 1 : 0;
    this.on = new Value(initialValue);
    const animation = new Value(initialValue);
    this.animation = set(
      animation,
      runTiming2(new Clock(), animation, {
        easing: Easing.inOut(Easing.ease),
        duration: 300,
        toValue: this.on
      })
    );
  }

  componentDidUpdate() {
    this.on.setValue(this.props.on ? 1 : 0);
  }

  render() {
    const width = interpolate(this.animation, {
      inputRange: [0, 1],
      outputRange: [50, 200]
    });
    const height = interpolate(this.animation, {
      inputRange: [0, 1],
      outputRange: [50, 100]
    });
    return (
      <Animated.View
        style={{
          width,
          height,
          backgroundColor: 'red'
        }}
      />
    );
  }
}

class App extends React.Component {
  state = { on: false };

  render() {
    const { on } = this.state;
    return (
      <View>
        <View
          style={{
            width: '100%',
            height: 400,
            justifyContent: 'center',
            alignItems: 'center'
          }}
        >
          <TogglingThing on={on} />
        </View>
        <TouchableOpacity
          style={{
            height: 48,
            width: '100%',
            backgroundColor: 'salmon',
            alignItems: 'center',
            justifyContent: 'center'
          }}
          onPress={() => this.setState(state => ({ on: !state.on }))}
        >
          <Text style={{ fontSize: 30, fontWeight: 'bold' }}>
            {on ? 'ON' : 'OFF'}
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

### CODE REVIEW

**Comment by wcandillon** [comment]
Thanks a lot guys! @marcusstenbeck Can you rebase these three commits and use a semantic commit message? As soon as this is done, I will merge it.

**Comment by marcusstenbeck** [comment]
@wcandillon Done!

It'd probably be nice to get a similar thing in for the other animation runners. Shall I create an issue for it?

**Comment by wcandillon** [comment]
Thank you!

**Pull request merged**
