### PR TITLE
💄 Improvements in SVG Path Morphing

### LINKED ISSUE #49: Normalize interpolation functions
Currently, we have `interpolate` and `bInterpolate` from redash. I use these functions all the time and they make a lot of sense. However for path and color interpolation, the functions signatures are not symmetric with `interpolate` and `bInterpolate`. I would be nice to do some cleanup there.

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #49

### CODE REVIEW

**Comment by wcandillon** [comment]
@dsznajder as seen here: https://twitter.com/wcandillon/status/1137669530635948033

**Comment by dsznajder** [comment]
@wcandillon Sorry I did not respond earlier. :fire: It's really Awesome

**Comment by wcandillon** [comment]
Thanks a lot :) That's a breaking change indeed :)

**Pull request merged**
