### PR TITLE
modify ReText to set animated value, string or number, as placeholder…

### PR DESCRIPTION
**Pull request by aalbaharnah**
modify ReText to set animated value, string or number, as placeholder prop in the component and then display it as text

- ali

### CODE REVIEW

**Comment by wcandillon** [comment]
I have great news. Reanimated v1.3.0 has been shipped and fixes this bug on android. Can you give it a try? If you would like to merge this PR anyways, there should be a ReText.android.tsx and a ReText.ios.tsx file. These are not well supported by TS I think however 🤔

**Comment by wcandillon** [comment]
I'm enclined to not ship the setNativeProps option but we should document it.

**Comment by aalbaharnah** [comment]
Oh yeah, no problem. I'll try reanimated ^1.3.0 and see if it works. 👍

**Comment by wcandillon** [comment]
It is confirmed now that `ReText` works well on `1.3.0` closing this PR for now. However, I don't have an objection to eventually offer such a mechanism with `setNativeProps` if necessary.

**Pull request closed without merging**
