### PR TITLE
fix(🐛): Enable package for lower version of Babel

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@marcusstenbeck can you confirm redash works well in your "older" projects? I just want to make that there aren't other problems between redash and older RN versions.

**Comment by marcusstenbeck** [comment]
I'll work with it during the day today and report back.

**Comment by marcusstenbeck** [comment]
I wasn't able to work as much with it yesterday as I would have wanted, but in the hour or so I got I didn't run into any issues. :+1:

**Comment by wcandillon** [comment]
@marcusstenbeck sorry to be late in the game, releasing this today.

**Pull request merged**
