### PR TITLE
feat: add jsdoc annotations from documentation

### PR DESCRIPTION
**Pull request by doylemark**
Added JSDoc annotations for rich integration with IDEs (eg vscode). All summaries and examples taken directly from new redash documentation. 😄

image

### CODE REVIEW

**Comment by doylemark** [comment]
Any interest in merging this feature? If not I'll close and keep it on my own fork as they provide some usefulness for me at least :)

**Comment by Charly6596** [comment]
+1 to this, I don't see a reason to not have doc annotations, hope it gets merged

**Comment by wcandillon** [comment]
Sorry this felt into the cracks, will merge it ;-)

**Comment by doylemark** [comment]
awesome :)

**Pull request merged**
