### PR TITLE
runLoop()

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@dsznajder Not as composable as we would like it to be but definitely a step in the right direction :)

**Comment by dsznajder** [comment]
@wcandillon  I'm just thinking, shouldn't it goes from 0 to 1 constantly instead of "boomerang"?

**Comment by wcandillon** [comment]
@dsznajder we need an option to have both right?

**Comment by dsznajder** [comment]
@wcandillon Probably, but If it fits already your needs we can merge it and add some issue tracker :)

**Comment by wcandillon** [comment]
@dsznajder I added the `boomerang` option and it works great! The clock parameter should be optional too right? And it looks like there is no way to interrupt this loop animation at the moment 🤔

**Pull request merged**
